### ISSUE TITLE
Dual screen problem

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#1]
I have 2 monitors. To start softhddevice on my secondary monitor I'm using its geometry parameter (-g). But vdr-plugin-mpv doesn't have this parameter ( it was present in the deprecated vdr-play) so I can start softhddevice on my secondary monitor but when I open a video with vdr-plugin-mpv the video start on my primary monitor. Could you insert the geometry parameter on vdr-plugin-mpv to make it working on a dual screen setup please?

**Comment by ua0lnj** [comment]
How do you set up a second monitor with geometry?
Are you using absolute geometry?

**Comment by nikjsu** [comment]
Yes I confirm I'm using absolute geometry with the plugin softhddevice starting vdr with "vdr -Psofthddevice -v vdpau -g 2048x1152+1920+0 " to have vdr on my secondary monitor. but when I start a video with vdr-plugin-mpv the video open on my first monitor while vdr is still visualized on my secondary monitor.
I've noticed that also the mpv program has an option to choose the monitor/screen. I've tested  "mpv --screen=1" that launch a video on my secondary monitor and "mpv --screen=0" to start a video on my first monitor.
Is it possibile for you add a vdr-plugin-mpv command line option to  to specify these mpv parameters?
Hope you can help me. My only actual solution is using xineliboutput plugin but I would prefer to swith to softhddevice+vdr-mpv.  Just to be more precise I'm using deepin linux on a manjaro system.

**Comment by ua0lnj** [comment]
Done.
https://github.com/ua0lnj/vdr-plugin-mpv/commit/68fe0c632230fa2f97c57d5574a0f565d2020a79
