### ISSUE TITLE
geometry option dosn't go fullscreen

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#2]
Hi thanks for your help. I've tested your fix launching vdr vith -P"softhddevice -v cuvid 1980x1080+1920+0" -P"mpv -g 1980x1080+1920+0".  The mpv window open on the correct location with the correct size on my secondary monitor but not in fullscreen. I have it windowed (with the mpv tittle bar). I've replicated the behavior with mpv app (without vdr) and I've noticed that to have fullscreen I have to add the -fs mpv parameter in this way: "mpv -fs --geometry=1980x1080+1920+0 movie.mp4". could you add the -fs parameter to vdr-mpv-plugin please? ( Instead without geometry parameter I have automatically fullscreen though on my first monitor)
I've also noticed that the softhddevice geometry parameter too doesn't work at all. the -g 1920x1080... it's not taken in consideration (xineliboutput  have the same parameter and it work perfectly on my system). for now I'm using the mouse to move it on my secondary monitor but when a restart happens......it return on my first monitor. hope you can fix this too. Thanks in advance for your help and for your efforts improving this software.

**Comment by ua0lnj** [comment]
Hm...
I've made fullscreen and manual geometry mutually exclusive.
The plugin was always full screen, only for manual gemetry I made a windowed mode.
Then I'll do it a little differently.

**Comment by ua0lnj** [comment]
Done.
https://github.com/ua0lnj/vdr-plugin-mpv/commit/801c113521dc3e23284052fbdfa4cbdaf660b3ca

**Comment by nikjsu** [comment]
Yes. now it works very well and good idea to have added the -w commandline . I've opened a ticked for geometry in  softhddevice too. hope you can fix that too when you have time.
