### ISSUE TITLE
Why not to switch to ffplay/ffmpeg instead mpv?

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#3]
Hi. I'm continuing testing your mpv plugin but I'm noticing I'm not so confortable like using the internal player in xineliboutput ( i like the player but I hate the xine libraries) or the internal player of the very old softdevice. For exemple I would to ask you to change the bahavior of the "back key" to return to the directory of the video played but I suppose it's not possibile (after a video is started it's not possible return to browse directories without starting from softhddevice menu). The very old softdevice was perfect using its internal player. the switch from softdevice to softhddevice  has left us without internal media player and you are trying with good results to cover this missing. In many years no one have tried to restore that functionality. Softhddevice use ffmpeg like softdevice. why not build an internal player using the ffmpeg libraries and programs like ffplay like it was in the old softdevice plugin? I know that mpv is the best player but is always an external player. I'm ignorant about coding. I don't know if it's too diffucult to build an internal player using ffmpeg. mine it's just a suggestion a and I continue to tahnk you for your work.

**Comment by ua0lnj** [comment]
There is an idea to do the opposite, so that vdr outputs video via mpv :)
Using a ready-made player is easier than writing your own. Not all the potential of MPV as a plugin is exhausted.
OpenGL OSD can be done, but it requires major improvements and a lot of time. 

Do you want to play another video when the player is playing? For what you want to return to the directory of the video played?

**Comment by nikjsu** [comment]
I was thinking that using the internal ffmpeg player ffplay would give a better integration but probably we have the same limitations with a worst player so I can understand your explanation. I've noticed that the softhddevice-drm fork now have it's internal player. I wonder if it's possible more or less easily use that code for this purpose.
I've already tried the streamdev mpv script but loosing the vdr osd it's out of discussion. I prefer your approach. About your last question I often watch sequentially tv series or anime episodes so I finish episode 1 I click "back" key  and I click  "play" on episode 2 and the same for the other episodes also sometimes I watch many videos from different directories so I often use the back key in xineliboutput internal player to return on my actual directory or to move to other directories. the "back" key maybe is the key I use more after the play key. But if  have this option need too work I can understand.

**Comment by ua0lnj** [comment]
I'll think about making it possible to return to the video catalog. But you can also play an entire directory rather than a single file. It is more comfortable?

**Comment by nikjsu** [comment]
about video catalog you mean the root directory called with "-b /dir" or the directory of the video file I'm playing (=the last directory I've opened)? The last would be ideal. Yes I hope you can find a good solution.

**Comment by ua0lnj** [comment]
I mean last directory.
And you can press GREEN key when select a directory in browser mode, mpv create playlist and play all files in directory.
So as not to run the next file manually.

**Comment by nikjsu** [comment]
Yes understand what you mean. it's not the same thing that browsing and playing singles files but it can help in some scenarios. Now I'm testing some scripts to have a file browser in mpv window in particular Blackbox.js but I don't know if mpv plugin can load only lua scripts or the java scripts too and if I can start these scripts I don't know if I can use the remote keys to use these scripts. I let you know if I'll have good results.

**Comment by nikjsu** [comment]
I think is correct close this ticket. I prefer open a one more specific
