### ISSUE TITLE
mpv-file-browser lua script integration

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#4]
Hi I've talked with you about the possibilty to browse directories and returning back to the last directory. I've found this lua script https://github.com/CogentRedTester/mpv-file-browser. It's seem to me perfect for this purpose. I've used yesterday with mpv software (not the vdr plugin) with success. your vdr-mpv plugin  give the possibility to use  mpv with lirc ( mpv only software  is very difficult to use with a remote control) and it can load lua scripts. 
I've tried to load this lua script wih vdr-mpv plugin but how can I be sure if the lua script is loaded? on my logs i can't see this info and I don't know if it's possible assign keybinding using a lua script with the plugin.

**Comment by ua0lnj** [comment]
I think, browse directories should be done through a plugin's menu and not external scripts.
Now I have other tasks, then I will look at this.

**Comment by nikjsu** [comment]
Good to know it. Ok so take your time. I can wait patiently. my priority was the geometry problem and you have fixed quickly. Thanks again.

**Comment by ua0lnj** [comment]
I think this is what you wanted :)
See https://github.com/ua0lnj/vdr-plugin-mpv/commit/5c09255f1126cc3f07204a1bbd67b27882ff0595

**Comment by nikjsu** [comment]
Thank you Andrey. Yes that was my need. Yesterday I've completely switched from xinelibout to softhddevice+vdr-mpv with cuda with a big satisfaction ( finally softhddevice without av-sync problems and with a good media player). Now I'm knowing and testing better this plugin and I've noticed some things that could  be improved if you can and when you have time. The back key now is perfect but I've noticed that while watching a video I can click the menu button and in the menu I can click again mpv in this menu'. would be good open the "-b /dir" root directory (when is setted) with this path keeping the back key for the last directory. naturally it's not fundamental and it can be postponed. Another thing I've noticed are the video.resume files. they need to be hidden to the player. they are counted in the playlist too. Unfortunately I've notices a very annoying problem too with videos with multi languages and subtitles but I think it's better open a new ticket. Thanks again and I was forgetting....happy new year.

**Comment by ua0lnj** [comment]
Now, when you select MPV in the main menu, you see the file directory or the options menu, depending on what you chose and the last time. If you pressed back before, you will go to the file directory, if you pressed blue before, you will go to the function menu. Probably it is not very convenient, while the question is. About video.resume understood, I'll take a look.

**Comment by nikjsu** [comment]
Yes I understand.  Anyway you've done a great job. I'm very satisfied . So I close this ticket. Just a little note. I've added manually two keys like the vdr adaptive skipping function, setting key 1&3 to skip 15 seconds. that's a simple cut and past to the keyGreen and keyYellow in control.c file. I think you can consider to add these few lines. these key's are very confortable while watching a video.
