### ISSUE TITLE
resume play feature

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#5]
Hi I've noticed you've tried to hidden .resume files. unluckily the last commit hasn't worked. Also I've realized that the mpv-plugin doesn't let to resume videos when they are interrupted. that would be a good feature especially with long movies. I mean  to reproduce the same behavior of vdr recordings window or xineliboutput player. when you select a video and that video was previously interrupted  a green "rewind" field appears. if that video hasnt been interrupted in the past then the green field doesn't appear. I know mpv doesn't store video status with default options. it needs "save-position-on-quit" parameter and it doesn't create the .resume extension. In mpv-plugin it can be seated default or like an option selectable in the plugin option page. Hope you can add this feature too when you have time.

**Comment by ua0lnj** [comment]
Describe the situation with resume files. I just made that they are not added to the playlist when playing the entire catalog.

**Comment by nikjsu** [comment]
The situation with .resume files it's only an anesthetic problem not a functional problem so i cannot consider it a big issue but just a software improvement.  Ok I have a folder with 5 videos and their associated 5.resume files ( probably created from other video players). Then using the mpv-plugin I click the playdir button and under the title on the right I can read the number 10 but the expected number should be 5. the mpv-plugin can skip the .resume files seen that clicking the key9 it go from video1 to 3-5-7-9. But the correct behavior would be have a playlist with only 5 files so the skip sequence have to be 1-2-3-4-5. Probably these screenshots explain better than my words ( the number 10 should be 5).
![DeepinScreenshot_seleziona-area_20210103105424](https://user-images.githubusercontent.com/75567277/103476841-77417880-4db9-11eb-8a20-5b7b876bc1f2.png)
![Schermata del 2021-01-03 11 40 44](https://user-images.githubusercontent.com/75567277/103476842-77da0f00-4db9-11eb-9489-956ae3928be9.png)

**Comment by ua0lnj** [comment]
I tested again, and you are right.
What i did works for file names but not file extension.

**Comment by nikjsu** [comment]
Yes thanks. now it's working. I've noticed another little bug testing this commit. if you click playdir button to one folder without video files for example an empty directory  the vdr going in crush. on my system I have black screen then the only thing to do is kill the vdr process.

**Comment by nikjsu** [comment]
I've tested now your last commit about the crash playing empty directory but it seem to me that it down't solve. I still have black screen. I've also noticed that the keyyellow (shuffle) doesn't work.

**Comment by ua0lnj** [comment]
Added https://github.com/ua0lnj/vdr-plugin-mpv/commit/2b9bab973f73eb260d66f2644fabdcc65266cc12

**Comment by nikjsu** [comment]
Hi first of all thanks to working on this feature too. I've tested your last commit. The resume is working only using the stop key. With other quit cases  like restarting vdr,  killing vdr, a pc crash or  switching directly to another video the quit  position is not saved. Hope you can add the rewind green field too like in vdr recordings.

**Comment by ua0lnj** [comment]
It was intended. MPV saves the position only when the correct exit. Maybe it can be improved.

**Comment by nikjsu** [comment]
Ah ok I understand. I've noticed that the mpv program too saves the position only pressing the q key. It's an mpv limit. It's not like vdr recording save position but at least for the current vdr-mpv session is useful. Thanks
