### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by fiveten59** [ua0lnj/vdr-plugin-mpv#7]
Attached Italian translation.
Thanks for you great job
[it_IT.po.tar.gz](https://github.com/ua0lnj/vdr-plugin-mpv/files/5897718/it_IT.po.tar.gz)

**Comment by ua0lnj** [comment]
Added.
https://github.com/ua0lnj/vdr-plugin-mpv/commit/581667b899cc9bc37d3664d91c663c9e69e7fb63
