### ISSUE TITLE
volume level too much  lower than vdr

### ISSUE THREAD

**Issue by nikjsu** [ua0lnj/vdr-plugin-mpv#8]
Hi. I've always noticed a big discrepancy between mpv-plugin and vdr volume levels. Using mpv-plugin i have to raise the volume then going back to vdr live watching I have to lower the volume.
To be sure I've recorded a tv channel. First I've played the recorded channel  with vdr then with mpv-plugin I've browsed my vdr recording folder and I've opened the corresponding .ts file . In this way is easy to notice a big difference. Could you adjust the mpv-plugin to have the same volume level as vdr please?

**Comment by ua0lnj** [comment]
Interestingly, on the contrary, I did not notice this.
You use passthrought?

**Comment by nikjsu** [comment]
No nothing passthrough. I have the simpliest configuration. the classic desktop with two monitor without need special audio settings. I have all "no" in softhddevice audio options and "no" in passthrough and downmix in mpv-plugin options. I've tried on manjaro kde and manjaro deepin but I have the same result. without pulseaudio support on softhddevice I can't  see the volume level on a mixer so only my ears can notice this problem. Do you know if  is there a way to see this volume change using alsa?

**Comment by ua0lnj** [comment]
Try alsamixer in console.

**Comment by nikjsu** [comment]
On alsamixer I have only the master volume. this doesn't change when I change the vdr volume. To see the mixer volume change I would need the hardware volume control working in softhddevice. only software volume control is working.another solution would be the pulseaudio support to see the volume app but we can choose only alsa. I don't know if these ai another way to demonstrate this problem. i've tried with some mixers but in general it's seem to me it's not possible to visualize the volume level of vdr outside vdr.

**Comment by nikjsu** [comment]
I'm investigating. First I've noticed that without -a alsa mpv-plugin option I have no audio. in the log I have Audio output alsa:device=default not found! Could not open/initialize audio device -> no sound ( is it normal?). Then I'm suspecting that using -a alsa probably give mpv 7.1 channels having probably vdr with 2.1 channels so that could justify the lower audio.

**Comment by nikjsu** [comment]
Ok I've tested. I confirm there's a problem. I've tested many audio config with mpv without problems but I don't know why mpv-plugin accept only -a -alsa/default ( I've read the vdr news forums threads too but  they haven't helped me) so I've used this. 
I've just tryied mpv compiled  with --disable-pulseaudio. Same result. i't's not an alsa/pulseaudio problem. To have the same volume levels I have to use the softhddevice option "reduce stereo volume" at about 300 ( it's a big difference).

**Comment by nikjsu** [comment]
I've tested using -a pulse too. I have the identical behavior as -a alsa/default

**Comment by ua0lnj** [comment]
Can't reproduce.
I use -a alsa/front:CARD=Intel,DEV=0 for mpv plugin and -a front:CARD=Intel,DEV=0 for SHD
Also works -a alsa/surround51:CARD=Intel,DEV=0 for mpv plugin and -a surround51:CARD=Intel,DEV=0 for SHD.
All works fine with same audio level.
-a -alsa/default giving PulseAudio error.

But...
I was able to reproduce this 1 time when I turned off passthrough on the over vdr. The sound of the mpv plugin turned out to be 2 times quieter (50%), but I just added the volume to 100% and everything became normal, the volume does not change anymore.
You can run alsamixer, press F6, select audio card (Intel?) and looking level.

**Comment by nikjsu** [comment]
We have a very similar audio hardware (Intel). I've read so many posts in these days and finally I've solved my audio mixer problems with softhddevice modifying the /etc/pulse/default.pa like suggested in the arch pulseaudio wiki page. Now I can set hardware volume control and I can see the the softhddevice volume level changes. But using the mpv-plugin the levels on the mixer doesn't change raising or lowering the volume. it is the same for you I suppose.I've used your tip too and I'm using -a alsa/front:CARD=PCH,DEV=0 for mpv-plugin and -a front:CARD=PCH,DEV=0 for shd ( and the surround too) but unluckily the situation doesn't change.
I would ask you if you can add this trick to give to mpv-plugin the volume level on alsamixer  https://github.com/mpv-player/mpv/issues/3322. I've tested it with mpv and it works. So that I can open the .ts file with mpv and mpv-plugin and made another comparison. the option volume-max=value could help too. or why don't give mpv-plugin the possibility to read the mpv.conf and input.conf?

**Comment by ua0lnj** [comment]
Try
At the end of player.c
replace line
SendCommand("set volume %d\n", Volume);
on
mpv_set_property_string(hMpv, "ao-volume", std::to_string(Volume).c_str());

and test it.

**Comment by nikjsu** [comment]
Ok I've tested. I've started softhddevice with -a front:CARD=PCH,DEV=0 -c Master and mpv-plugin with -a alsa/front:CARD=PCH,DEV=0. So now I have softhddevice ( with hardware volume control) and mpv-plugin both working on alsamixer channel Master.  Now the behavior is changed but still problematic but it's easier to explain. I've started watching a tv channel  and I've chosen to put the volume to 88 on Master. then I open with mpv-plugin the .ts file (or another video) and the volume stay at level 88 ( how it has to be) but when I stop mpv-plugin the volume switch automatically from 88 to 34. I've tried to understand why 34 and I've discovered that 34 is exactly the last volume I had on softhddevice when I've restarted it. I've tried other softhddevice volume levels but every time I stop mpv-plugin the volume go to 34. Naturally if I restart vdr while having volume level to 66 then switching back from mpv-plugin to softhddevice will reset the volume always to 66.

**Comment by nikjsu** [comment]
I've continued testing. So what I've understood is that when I stop mpv-plugin, softhddevice doesn't keep the volume level I was having playing a video with mpv-plugin  but it reads the parameter "initial volume" in the vdr setup miscellaneus. On my siystem it was setted "as before" and this explains the discrepancy on volume level switching between softhddevice and mpv-plugin. Now I've changed "as before" to 0 and in this way softhddevice remember the volume level but it's muted and I have to click the volume key on my remote to unmute it. Hope you can make a perfect integration between softhddevice and mpv-plugin.

**Comment by ua0lnj** [comment]
Reproduced.
This is not mpv plugin trouble, vdr restores the volume at the time of start, it is necessary to modify the softhddevice.

**Comment by ua0lnj** [comment]
Try it.
Update the plugins softhddevice and mpv.

**Comment by nikjsu** [comment]
I've tested latest commits but unfortunately the situation remains almost the same. I'll explain the behavior with my old example: I set  softhddevice volume to 88 then I play a video with mpv-plugin and the volume correctly stay at 88. then I turn down the video volume until 38 ,I stop mpv-plugin and the volume go directly to 88 on softhddevice. but as soon as I click my remote volume key (just one click) the volume switch directly to 38. I would have expected to have 38 smootly switching from mpv-plugin to softhddevice.

**Comment by ua0lnj** [comment]
Yes, this case is not done.
I didn't save the level in the plugin, but I understood the idea.

**Comment by ua0lnj** [comment]
Try now.

**Comment by nikjsu** [comment]
Now the volume level I can see on alsamixer switching between softhddevice and mpv-plugin and vice versa are correctly saved. But there is a big problem. The mpv-plugin volume I can ear doesn't corresponds to  alsamixer volume level I can see. It's much lower. the worst situation happens starting  mpv-plugin when softhddevice volume is very low.  If I put softhddevice volume from 0 to 5 for example and I start a video with mpv-plugin I can raise the volume until 100 too (I can see it on alsamixer) but I can't hear the sound. It's seem to me that a perfect sync between mpv-plugin and softhddevice and between mpv-plugin and alsamixer happens only starting mpv-plugin when softhddevice volume level is 100.

**Comment by nikjsu** [comment]
I've made other tests. I've tried using mpv without pulseaudio support too but nothing changes. What I can say is that setting softhddevice and mpv-plugin in software volume control makes this problem less annoying but harder to identify. Anyway the easier way to reproduce this issue is setting softhddevice and mpv plugin in hardware volume control. then start vdr and put the softhddevice volume at minimum. open a file with mpv-plugin. now  raise the volume how much you want and you can notice you can't hear the sound although alsamixer says you have volume.

**Comment by ua0lnj** [comment]
Found it.
Fixed.

**Comment by nikjsu** [comment]
Thanks Andrey. I've tested the last fix. Now with hardware volume control the softhddevice and mpv plugin volume is identical and working perfectly. I've tested it with software volume control too and in this case unluckily the mpv plugin volume remains lower than softhddevice but I don't know if it's fixable or not and how many efforts it needs and I know you're working on other tasks too. I'm satisfied setting hardware volume control. So if you prefer you can close this ticked.

**Comment by ua0lnj** [comment]
Software volume control MPV has 150 level units, so maybe there is a difference.
